### ISSUE TITLE
Kindly add herokku support

### ISSUE THREAD

**Issue by rsoorajs** [andrepcg/roasted-mail#1]
if you can add a herokku button for easy deploy..
or write a read me

**Comment by telegrambotdev** [comment]
when i checked the heroku logs


2020-06-27T06:07:51.503658+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "logs" does not exist
2020-06-27T06:07:51.503658+00:00 app[web.1]: LINE 8:  WHERE a.attrelid = '"logs"'::regclass
2020-06-27T06:07:51.503658+00:00 app[web.1]:                             ^
2020-06-27T06:07:51.503659+00:00 app[web.1]: ):
2020-06-27T06:07:51.503659+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670]   
2020-06-27T06:07:51.503659+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670] app/services/stats_producer.rb:12:in `email_stats'
2020-06-27T06:07:51.503659+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670] app/services/stats_producer.rb:7:in `block in call'
2020-06-27T06:07:51.503660+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670] app/services/stats_producer.rb:6:in `call'
2020-06-27T06:07:51.503660+00:00 app[web.1]: [933cec5a-d137-4e40-bc21-98114d0a9670] app/controllers/mailbox_controller.rb:8:in `index'
2020-06-27T06:07:51.506260+00:00 heroku[router]: at=info method=GET path="/" host=makeirhh.herokuapp.com request_id=933cec5a-d137-4e40-bc21-98114d0a9670 fwd="117.223.191.190" dyno=web.1 connect=1ms service=12ms status=500 bytes=1827 protocol=https

**Comment by telegrambotdev** [comment]
![IMG_20200627_113949_689](https://user-images.githubusercontent.com/20116017/85916103-f2eec580-b86a-11ea-9d06-82d425c9a002.jpg)
